WIP: Como encontrar patrocindaores
AfroPython/Manual-do-evento pull request #13
Opened 2019-02-12 10:22 UTC by lipemorais

- [ ] Introdução
- [ ]  Como encontrar patrocinadores
- [ ] Modelo de E-mail
- [ ] Patrocínio do GitHub
- [ ] Como lidar com o dinheiro
- [ ] Patrocínios passados

2019-02-13 17:39 UTC, pedrro requested changes
Erros de português e algumas sugestões

2019-02-13 17:39 UTC, pedrro commented on patrocinadores/encontrar_patrocinadores.md
> +Devido ao AfroPython ter como foco pessoas negras da região interessadas em tecnologia, nossos participantes são possíovels empregados e clientes de empresas que podem vir a patrocinar o evento.
```suggestion
possíovels
```
possíveis

2019-02-13 17:39 UTC, pedrro commented on patrocinadores/encontrar_patrocinadores.md
> +Nós buscamos por patrocinadores que são ativos na comunidade local de tecnologia, de starups até grandes corporações mesmo organizações não governamentais(ONGs).
startups

2019-02-13 17:39 UTC, pedrro commented on patrocinadores/encontrar_patrocinadores.md
> +AfroPython devem ser sempre mantido como não lucrativo: Caso tenha sobra de dinheiro, deve ser utilizado para apoiar outros eventos como encontros do AfroPython, confraternização ou doado para a [Pyt
```suggestion
O evento AfroPython deve ser sempre mantido como não lucrativo: Caso tenha sobra de dinheiro, deve ser utilizado para apoiar outros eventos como encontros do AfroPython, confraternização ou doado para a [Python Software Foundation](https://www.python.org/psf/) que sempre nos apoia nesses eventos. Não se esqueça que você não precisa de dinheiro, e que até uma pequena startup pode ajudar. Pode inclusive ser mais fácil der várias pequenas empresas patrocinando do que uma empresa gigantesca.
```

2019-02-13 17:39 UTC, pedrro commented on patrocinadores/encontrar_patrocinadores.md
> +O mais importante é: **nunca dê dados de nenhuma das pessoas envolvidads(nomes, e-mails, ou qualquer outra informação).** Nós somos muito comprometidos com a privacidade de cada pessoa. Você não deve
```suggestion
O mais importante é: **nunca dê dados de nenhuma das pessoas envolvidas(nomes, e-mails, ou qualquer outra informação).** Nós somos muito comprometidos com a privacidade de cada pessoa. Essa regra não deve ser quebrada, nem que isso possa significar a perda de um patrocínio, brindes ou local para a oficina. Apenas não faça isso.
```

2019-02-13 17:39 UTC, pedrro commented on patrocinadores/encontrar_patrocinadores.md
> +Você pode enviar e-mails aos participantes sobre os patrocinadores, mas não pode compatilhar nenhuma informação sobreas pessoas envolvidas com patrocinadores.
```suggestion
Você pode enviar e-mails aos participantes sobre os patrocinadores, mas não pode compatilhar nenhuma informação sobre as pessoas envolvidas com patrocinadores.
```

2019-02-13 17:39 UTC, pedrro commented on patrocinadores/encontrar_patrocinadores.md
> +É o que que patracinadores falem com as pessoas nos eventos desde que que não atrapalhe ou seja inconveniente para quem participa.
```suggestion
E o que patrocinadores falem com as pessoas durante os eventos, desde que não seja inconveniente com quem participa.
```

2019-02-13 17:39 UTC, pedrro commented on patrocinadores/encontrar_patrocinadores.md
> +## O que você pode oferece?
```suggestion
## O que você pode oferecer?
```

2019-02-13 17:39 UTC, pedrro commented on patrocinadores/encontrar_patrocinadores.md
> +A oferta comum aos patrocinadores é que eles possam mostrar seus produtos ou serviçop para as pessoas que estão participando do evento. Isso talvez inclua:
```suggestion
A oferta comum  feita aos patrocinadores é que eles possam mostrar seus produtos ou serviços para as pessoas que estão participando do evento. Isso talvez inclua:
```

2019-02-13 17:39 UTC, pedrro commented on patrocinadores/encontrar_patrocinadores.md
> +- alguns minutos para falar durante o evento
```suggestion
- alguns minutos de fala durante o evento
```

2019-02-13 17:39 UTC, pedrro commented on patrocinadores/encontrar_patrocinadores.md
> +Recomendamos falar com os patrocinadores e perguntas sobre seus objetivos ao patrocinar o evento. Nós sempre tentamos colaborar com nossos parceiros e ter certeza que todos estamos atingindo nosso ob
```suggestion
Recomendamos perguntar aos patrocinadores sobre seus objetivos ao patrocinar o evento. Nós sempre tentamos colaborar com nossos parceiros e ter certeza que todos estamos atingindo nosso objetivos e entregando o valor esperado.
```

2019-02-13 17:39 UTC, pedrro commented on patrocinadores/encontrar_patrocinadores.md
> +Se você tiver um tempinho para isso, nós recomendamos fortemente a criação de um plano simples de patrocínio - Um PDF com algumas páginas. Diga quem é você, o que é o AfroPython e porque é incrível,
```suggestion
Se você tiver um tempinho para isso, nós recomendamos fortemente a criação de um plano simples de patrocínio - Um PDF com algumas páginas. Diga quem é você, o que é o AfroPython e porque é incrível participar deste evento, quem vai vir ao evento e sobre quão a importância de patrocinar esse evento.
```

2019-02-13 17:39 UTC, pedrro commented on patrocinadores/encontrar_patrocinadores.md
> +- Procure pod eventos parecidos nas sua cidade com Django Girls e Rails Girls e entre em contato com as empresas que costumam apoiar esses eventos.
```suggestion
- Procure por eventos parecidos nas sua cidade como por exemplo, Django Girls e Rails Girls e entre em contato com as empresas que costumam apoiar esses eventos.
```

2019-02-13 17:39 UTC, pedrro commented on patrocinadores/encontrar_patrocinadores.md
> +- A [Python Software Foundation (PSF)](https://www.python.org/psf/) costuma fornecer \$25 dólares por participante para oficinas como essa e ele consideram que podem apoiar até 2 oficinas como essa p
```suggestion
- A [Python Software Foundation (PSF)](https://www.python.org/psf/) costuma fornecer \$25 dólares por participante para oficinas como essa e ele consideram que podem apoiar até 2 oficinas como essa por ano, a diferença precisa ser de pelo menos 6 meses entre os eventos. Tenha em mente que a PSF é uma organização sem fins lucrativos, antes de pedir ajuda, **peça a empresas locais**. Para pedir patrocínio a PSF siga as instruções [no site deles](https://www.python.org/psf/grants/).
```

2019-02-13 17:39 UTC, pedrro commented on patrocinadores/modelo_email.md
> +Simplesmente mande um e-mail como esse:
```suggestion
Para entrar em contato com os patrocinadores, você pode utilizar um modelo como esse:
```

2019-02-13 17:39 UTC, pedrro commented on patrocinadores/modelo_email.md
> +Meu nome é COLOQUE_AQUI_SEU_NOME e sou uma das organizadoras do AfroPython em Porto Alegre. O AfroPython é um movimento brasileiro sem fins lucrativos que ajuda pessoas negras a se envolver com tecno
```suggestion
Meu nome é COLOQUE_AQUI_SEU_NOME e sou uma das organizadoras do LOCAL_DO_EVENTO em Porto Alegre. O AfroPython é um movimento brasileiro sem fins lucrativos que ajuda pessoas negras a se envolver com tecnologia através da programação de computadores.
```

2019-02-13 17:39 UTC, pedrro commented on patrocinadores/modelo_email.md
> +Estamos fazendo nosso primeiro envento em Porto Alegre no dia COLOQUE_AQUI_A_DATA e nós adorariamos ter você conosco. Estamos em busca de patrocinadores que podem nos ajudar a custear uma oficina de
```suggestion
Estamos fazendo nosso primeiro evento em LOCAL_DO_EVENTO no dia COLOQUE_AQUI_A_DATA e nós adorariamos ter você conosco. Estamos em busca de patrocinadores que podem nos ajudar a custear uma oficina de programação com almoço, lanches, brindes e outras recursos para realizarmos o evento.
```

2019-02-14 12:16 UTC, thayseonofrio approved these changes
👍🏽fiz algumas alterações nos arquivos direto no PR, mas tudo certin

2019-02-15 13:47 UTC, pedrro commented on patrocinadores/encontrar_patrocinadores.md
> +
Existe algum tipo de empresa que não gostariamos de contactar? Industria de armas, pornografica, ou que tenham algum histórico de racismo por exemplo

2019-02-15 13:48 UTC, pedrro commented on patrocinadores/encontrar_patrocinadores.md
> +Você pode usar o [plano de patrocínio](https://github.com/DjangoGirls/resources/tree/master/For%20Sponsors) preparado por nós.
o link referencia o django girls, vamos manter ou adicionaremos o nosso?

2019-02-15 13:49 UTC, pedrro commented on patrocinadores/encontrar_patrocinadores.md
> +- A [Python Software Foundation (PSF)](https://www.python.org/psf/) costuma fornecer \$25 dólares por participante para oficinas como essa e ele consideram que podem apoiar até 2 oficinas como essa p
```suggestion
- A [Python Software Foundation (PSF)](https://www.python.org/psf/) costuma fornecer $25 dólares por participante para oficinas como essa e ele consideram que podem apoiar até 2 oficinas como essa por ano, a diferença precisa ser de pelo menos 6 meses entre os eventos. Tenha em mente que a PSF é uma organização sem fins lucrativos, antes de pedir ajuda, **peça a empresas locais**. Para pedir patrocínio a PSF siga as instruções [no site deles](https://www.python.org/psf/grants/).
```

2019-02-15 13:49 UTC, pedrro approved these changes

2019-02-15 13:52 UTC, thayseonofrio commented on patrocinadores/encontrar_patrocinadores.md
> +
boa! talvez seja interessante algo como "contatar empresas que estejam de acordo com os valores explicitados no nosso código de conduta" ou algo assim

2019-03-21 00:54 UTC, lipemorais commented on patrocinadores/encontrar_patrocinadores.md
> +Você pode usar o [plano de patrocínio](https://github.com/DjangoGirls/resources/tree/master/For%20Sponsors) preparado por nós.
Não temos um nosso. Por enquanto podemos utilizar este até termos o nosso.

2019-03-21 01:05 UTC, merged