Criar Capitulo "Depois do evento"
AfroPython/Manual-do-evento pull request #26
Opened 2019-06-27 15:54 UTC by betinacosta

**Qual é o propósito deste Pull Request?**
- Adicionar o tópico "depois do evento" ao manual de organização com base no capitulo de "depois do evento" do manual do Django Girls;
- Corrige alguns probleminhas no sumário

**O que foi feito para alcançar esse propósito?**
Foi traduzido o material do Django Girls e feitas as devidas alterações para atender ao publico do AfroPython.

**Como testar se isso realmente funciona?**

- **Conteúdo:** Revisar o capitulo e verificar se as necessidades e filosofias adicionadas estão de acordo com o evento do AfroPython;
- **Visual:** Seguir esse [tutorial](https://til.secretgeek.net/gitbook/use_gitbook_locally.html) para instalar e roda o gitbook localmente;

**Quem pode ajudar a revisar este PR?**
Qualquer pessoa :)

2019-06-27 18:11 UTC, lipemorais commented on depois_do_evento/README.md
> +## Tabela de conteúdo do capitulo
Deveria ter um acento agudo no í de capítulo.

2019-06-27 18:20 UTC, felipythondev requested changes

2019-06-27 18:20 UTC, lipemorais commented on depois_do_evento/todo_list.md
> +Certifique-se de que os formulários sejam anônimos. Saiba que se voê perguntas os nomes de coaches por exemplo, o formulário deixa de ser anônimo.
você*

2019-06-27 18:20 UTC, lipemorais commented on depois_do_evento/todo_list.md
> +2. Numero de aplicantes
Número aqui precisa de acento também.

2019-06-27 18:20 UTC, lipemorais commented on depois_do_evento/todo_list.md
> +2. Numero de aplicantes
O que seriam os aplicantes?

2019-06-27 18:20 UTC, lipemorais commented on depois_do_evento/meetups.md
> +s
Sobrou um s aqui.

2019-06-27 18:20 UTC, lipemorais commented on depois_do_evento/meetups.md
> +Também é importante pedir feedback para conhecer melhor as necessidades do seu publico e seguir melhorando a cada Meetup.
A palavra público precisa de um acento aqui.

2019-06-27 18:59 UTC, ingridmurielem commented on depois_do_evento/exemplos_meetup.md
> +Essa sessão conterá exemplos de meetups do bem sucedidos do AfroPython. Sinta-se a vontade para contribuir.
`Essa sessão conterá exemplos de meetups já realizados pelo AfroPython. Sinta-se a vontade para contribuir.`

2019-06-27 18:59 UTC, ingridmurielem commented on depois_do_evento/todo_list.md
> +2. Numero de aplicantes
Vejo como número de aplicantes como número de inscritos ? 
talvez poderia colocar número de inscritos e número de selecionados
Acho interessante colocar o número de treinadores

2019-06-27 19:17 UTC, betinacosta commented on depois_do_evento/exemplos_meetup.md
> +Essa sessão conterá exemplos de meetups do bem sucedidos do AfroPython. Sinta-se a vontade para contribuir.
Valeu \o Corrigido em: c1d6fa620c5c5d0524a88ad7e2acf613aa2b6054

2019-06-27 19:17 UTC, betinacosta commented on depois_do_evento/meetups.md
> +Também é importante pedir feedback para conhecer melhor as necessidades do seu publico e seguir melhorando a cada Meetup.
Valeu \o Corrigido em: c1d6fa620c5c5d0524a88ad7e2acf613aa2b6054

2019-06-27 19:17 UTC, betinacosta commented on depois_do_evento/meetups.md
> +s
Valeu \o Corrigido em: c1d6fa620c5c5d0524a88ad7e2acf613aa2b6054

2019-06-27 19:18 UTC, betinacosta commented on depois_do_evento/todo_list.md
> +2. Numero de aplicantes
Valeu \o Corrigido em: c1d6fa620c5c5d0524a88ad7e2acf613aa2b6054

2019-06-27 19:18 UTC, betinacosta commented on depois_do_evento/todo_list.md
> +2. Numero de aplicantes
Valeu \o Corrigido em: c1d6fa620c5c5d0524a88ad7e2acf613aa2b6054

2019-06-27 19:18 UTC, betinacosta commented on depois_do_evento/todo_list.md
> +Certifique-se de que os formulários sejam anônimos. Saiba que se voê perguntas os nomes de coaches por exemplo, o formulário deixa de ser anônimo.
Valeu \o Corrigido em: c1d6fa620c5c5d0524a88ad7e2acf613aa2b6054

2019-06-27 19:18 UTC, betinacosta commented on depois_do_evento/README.md
> +## Tabela de conteúdo do capitulo
Valeu \o Corrigido em: c1d6fa620c5c5d0524a88ad7e2acf613aa2b6054

2019-06-27 19:20 UTC, felipythondev approved these changes

2019-07-03 21:46 UTC, betinacosta commented
Apliquei os comentários na PR @ingridmurielem e @lipemorais podem revisar se está ok para fazer merge?

2019-07-03 21:52 UTC, ingridmurielem commented
Opa, por mim pode Mergear @lipemorais tem alguma observação ?

2019-07-03 22:51 UTC, merged