Diy
AfroPython/Manual-do-evento pull request #30
Opened 2019-07-15 22:11 UTC by lipemorais

**Qual é o propósito deste Pull Request?**

Adicionar o tópico "faça você mesmo" ao manual de organização com base no capitulo de "DIY" do manual do Django Girls;

**O que foi feito para alcançar esse propósito?**
Foi traduzido o material do Django Girls e feitas as devidas alterações para atender ao público do AfroPython.

**Como testar se isso realmente funciona?**

_Conteúdo:_ Revisar o capitulo e verificar se as necessidades e filosofias adicionadas estão de acordo com o evento do AfroPython;
_Visual:_ Seguir esse tutorial para instalar e roda o gitbook localmente, dessa forma será possível visualizar o tópico de introdução para verificar como está esteticamente;

**Quem pode ajudar a revisar este PR?**
Qualquer pessoa :)

2019-07-15 23:28 UTC, ingridmurielem reviewed
Fiz algumas sugestões

2019-07-15 23:28 UTC, ingridmurielem commented on diy/README.md
> +Mas nós não queremos deixar a impressão de que para ter uma oficina de sucesso é preico ter toda a decoração, fazer vídeos e tudo mais. Nós acreditamos que essas coisas fazem a oficina especial mas a
aqui seria necessário trocar o preico por `preciso`

2019-07-15 23:28 UTC, ingridmurielem commented on diy/README.md
> +Se você encontrar um design legal (isso serve para foto, fonte, desenho, etc) que você adoraria usar durante o seu evento, **não se esqueça de verificar a licença.** Só utilize materiais que grátis o
Só utilize materiais **que** grátis ou pague pela licença de uso. 

Você pode remover este `que`

2019-07-15 23:28 UTC, ingridmurielem commented on diy/fotos.md
> +**Não se esqueça de validar se as pessoas se sentem confortáveis para serem fotografadas.**
vamos disponibilizar o documento  de autorização de imagem?

2019-07-16 00:05 UTC, pedrro requested changes

2019-07-16 00:05 UTC, pedrro commented on diy/README.md
> +Nós brilhamos ao tornar o tutorial do AfroPython uma experiência incrível. Se você der uma olhada nas fotos de outras oficinas verá que tem camisas incríveis, brindes e um monte de coisas legais. Ess
```suggestion
Nós brilhamos ao tornar o tutorial do AfroPython uma experiência incrível. Se você der uma olhada nas fotos de outras oficinas verá que tem camisas incríveis, brindes e um monte de coisas legais. Esses são elementos que fazem da oficina do AfroPython algo único e divertido.
```

2019-07-16 00:05 UTC, pedrro commented on diy/README.md
> +Este capítulo vai te dar dicas e exemplos, como - com um pouco de faça você mesmo, boas ideias e - você pode criar um experiência incrível com bem pouco dinheiro.
```suggestion
Este capítulo vai te dar dicas e exemplos de como criar uma experiência incrível com poucos gastos.
```

2019-07-16 00:05 UTC, pedrro commented on diy/README.md
> +Se você encontrar um design legal (isso serve para foto, fonte, desenho, etc) que você adoraria usar durante o seu evento, **não se esqueça de verificar a licença.** Só utilize materiais que grátis o
```suggestion
Se você encontrar um design legal (isso serve para foto, fonte, desenho, etc) que você adoraria usar durante o seu evento, **não esqueça de verificar a licença.** Só utilize materiais grátis ou pague pela licença de uso. Se não encontrar a licença, por favor não utilize.
```

Fiquei em dúvida de colocar no fim um `peça autorização ou não utilize`

2019-07-16 00:05 UTC, pedrro commented on diy/README.md
> +Se uma oficina tinha um lindo banner do AfroPython que você adoraria ter no seu onde as pessoas pudessem tirar fotos e você gostaria de ter no seu também. Vários das oficinas que compartilham decoraç
```suggestion
Várias das oficinas compartilham decorações, adesivos e brindes, então talvez alguma oficina ainda tenha alguns brindes disponíveis para doação, logo você não precisaria utilizar o seu orçamento para isso. Apenas peça o contato dos organizadores pelo e-mail do AfroPython para solicitar e talvez você possa ter alguns brindes emprestado a você.
```

Eu achei o exemplo do banner muito confuso, difícil de ler e sem conexão com o resto do paragrafo, então removi e tentei deixar mais fácil de entender.

2019-07-16 00:05 UTC, pedrro commented on diy/comida.md
> +# Comida é algo que tem em várias oficinas
```suggestion
# Comida
```
Para um título, eu removeria essa adição.

2019-07-16 00:05 UTC, pedrro commented on diy/comida.md
> +Esse é um elemento importante na oficina do AfroPython, a gente tenta ter pelo menos 2 refeições um lanche e uma refeição principal como almoço, mas o ideal é 3 com 2 lanches e uma refeição principal
```suggestion
Esse é um elemento importante na oficina do AfroPython, pois no caso de oficinas, geralmente elas podem durar o dia inteiro, então a gente tenta ter pelo menos 2 refeições um lanche e uma refeição principal como almoço, mas o ideal é 3 com 2 lanches e uma refeição principal para ninguém ficar com fome. **Não se esqueça de verificar as restrições alimentares, como alergias, veganos, vegetariános, celíacos, intolerâncias a leite e glúten, por exemplo.**
```

2019-07-16 00:05 UTC, pedrro commented on diy/decoração.md
> +Existem diferentes maneiras de deixar a oficina incrível. Se você é do tipo que gosta de decorar, preparar a decoração por ser fácil, apesar de tomar algum tempo. Se você não gosta desse tipo de cois
```suggestion
Existem diferentes maneiras de deixar a oficina incrível, como por exemplo ajudar na decoração do espaço, mas apesar de simples, pode parecer trabalhoso e tomar algum tempo. Para facilitar sua vida, nós temos algumas dicas para você também.
```

2019-07-16 00:05 UTC, pedrro commented on diy/decoração.md
> +* Algumas oficinas tem balões desses de festas mesmo que você pode encontrar em qualquer sessão de festas de super mercado ou uma papelaria. Esse são fáceis de encontrar e de encher com um pequeno gr
```suggestion
* Algumas oficinas tem balões de festas que você pode encontrar em qualquer sessão de festas de super mercado ou uma papelaria. Esse são fáceis de encontrar e de encher com um pequeno grupo de pessoas. _Dica: Tentem combinar com a cor da camisa dos participantes._
```

2019-07-16 00:05 UTC, pedrro commented on diy/decoração.md
> +Se quiser algumas inpsirações olhe as fotos das outras oficinas.
```suggestion
Mais dicas serão adicionadas ao longo do tempo, caso queiram algumas outras inspirações, não deixe de conferir as fotos das outras oficinas em nossos álbuns.
```

2019-07-16 00:05 UTC, pedrro commented on diy/extras.md
> +Não é sempre que se tem a grana para fazer camisas do AfroPython com aquelas capulanas maneiras para todas(os) participantes. Nós temos alguma dicas para preparar algo legal para participantes e trei
```suggestion
Nós sabemos que todos querem ter uma camiseta do AfroPython, mas também sabemos que não é sempre que se tem a grana para fazer nossas camisetas com aquelas capulanas maneiras para todas(os) participantes. Nós temos alguma dicas para preparar algo legal para participantes e treinadoras(es) sem precisar gastar uma fortuna nisso.
```

Acho interessante adicionar o link para o que é uma capulana.

2019-07-16 00:05 UTC, pedrro commented on diy/extras.md
> +- Em geral, pedir sacolas ecológicas são mais baratas do que pedir camisas, caso não se tenha grana para isso. De qualquer forma tome cuidado para que seja um produto que não estrague fácil antes de
```suggestion
- Em geral, pedir sacolas ecológicas são mais baratas do que pedir camisas, mas de qualquer forma tome cuidado para que seja um produto de qualidade antes de realizar o pedido. Nós já temos um modelo pronto para essas sacolas, sinta-se a vontade para mandar um e-mail para o AfroPython pedindo o modelo que usamos em eventos passados, mas também sinta-se a vontade criar novos modelos, lembrando sempre de respeitar as regras dos logos que estão descritas aqui neste manual.
```

2019-07-16 00:05 UTC, pedrro commented on diy/extras.md
> +- Se essas opções ainda forem mais caras do que o orçamento permite, pode se preparar pacotes pequeno com os brindes que foram oferecidos pelos patrocinadores. Algumas outras coisinhas com adesivos e
```suggestion
- Se essas opções ainda forem mais caras do que o orçamento permite, podem se preparar pequenos pacotes  brindes que foram oferecidos pelos patrocinadores. Algumas outras coisinhas com adesivos e bilhetes escritos a mão podem ser um ótimo presente, algo como "Muito obrigado por vir! Ubuntu!".
```

2019-07-16 00:05 UTC, pedrro commented on diy/extras.md
> +Não se esqueça o objetivo não é ter o mais caro e impressionante brindes para todo mundo mas sim mostrar para as pessoas como elas são importantes e nos importamos com ela. Apenas para fazer as pesso
```suggestion
Não se esqueça o objetivo não é ter o mais caro e impressionante brinde para todo mundo mas sim mostrar para as pessoas como elas são importantes e nos importamos com ela. Apenas para fazer as pessoas se sentirem especiais como são.
```

2019-07-16 00:05 UTC, pedrro commented on diy/fotos.md
> +Uma das coisas mais prazerosas de se olhar depois de um evento são as fotos que foram tiradas durantes ele, porém ter um fotógrafo profissional pode der caro. Por isso perguntar dentro das pessoas da
```suggestion
Uma das coisas mais prazerosas de se olhar depois de um evento são as fotos que foram tiradas durantes o mesmo, porém ter um fotógrafo profissional pode ser caro, por isso sempre é válido perguntar dentro das pessoas da organização se não tem alguém que tenha uma boa câmera e possa tirar as fotos. Caso não seja possível, procure por pessoas fotógrafas negras em sua região.
```

2019-07-16 00:05 UTC, pedrro commented on diy/fotos.md
> +Outra opção é criar um espaço onde as pessoas possam se reunir para tirar fotos. Poderia ser perto de um banner do AfroPython, por exemplo.
```suggestion
Outra opção é criar um espaço onde as pessoas possam se reunir para tirar fotos, como por exemplo um banner do AfroPython, uma mesa de comida ou apenas um espaço com luz.
```

2019-07-16 14:58 UTC, merged